---
- name: Tasks werden in unterschiedlichen Shells ausgeführt
  hosts: db1

  tasks:
    - name: Aktuelles Verzeichnis ermitteln
      ansible.builtin.command:
        cmd: pwd
      register: pwd_before

    - name: Aktuelles Verzeichnis ausgeben
      ansible.builtin.debug:
        var: pwd_before.stdout

    - name: In das übergeordnete Verzeichnis wechseln
      ansible.builtin.shell:
        cmd: cd ..

    - name: Aktuelles Verzeichnis erneut ermitteln
      ansible.builtin.command:
        cmd: pwd
      register: pwd_after

    - name: Aktuelles Verzeichnis erneut ausgeben
      ansible.builtin.debug:
        var: pwd_after.stdout
