[webservers]
web1
web2

[databases]
db1

[misc]
misc1

[training:children]
webservers
databases
misc

[physical]
dockerhost ansible_host=host.docker.internal ansible_user=sl01

[all:vars]
ansible_user=ansible
ansible_python_interpreter=/usr/bin/python3
