---
- name: Python-Skript mehrfach ausführen
  hosts: db1

  tasks:
    - name: Python-Skript auf den Managed Node kopieren
      ansible.builtin.copy:
        src: parameterized_pong.py
        dest: /tmp/parameterized_pong.py
        mode: "0755"

    - name: Python-Skript für mehrere Parameter ausführen
      ansible.builtin.command:
        cmd: /tmp/parameterized_pong.py {{ item }}
      loop:
        - Linux
        - Python
        - Ansible
