---
- name: Python-Skript auf db1 ausführen
  hosts: db1

  tasks:
    - name: Python-Skript auf den Managed Node kopieren
      ansible.builtin.copy:
        src: simple_pong.py
        dest: /tmp/simple_pong.py
        mode: "0755"

    - name: Python-Skript ausführen
      ansible.builtin.command:
        cmd: /tmp/simple_pong.py
      register: script_result

    - name: Ausgabe des Python-Skripts anzeigen
      ansible.builtin.debug:
        var: script_result.stdout
